repo:
  controller: config_pr.repo_controller.github
  repo_url: ''
  repo_user: marcellovani
  repo_name: test_config_pr
commit_messages:
  update: 'Updated config @config_name.yml'
  create: 'Created config @config_name.yml'
  delete: 'Deleted config @config_name.yml'
  rename: 'Renamed config from @config_name.yml'
